name: BridgeCrew Security Checks
env:
  TERRAFORM_ROOT_FOLDER : "modules"

on:
  pull_request:
    types: [opened, reopened]

jobs:
  scan_terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone this repo
      id  : git
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
        persist-credentials: true

    - name: Print nice message
      run : ls -la

    - name: Get changed files in the folder
      id  : changed-files-specific
      uses: tj-actions/changed-files@v35
      with:
#        dir_names: true
        files: |
          ${{ env.TERRAFORM_ROOT_FOLDER }}/**

    - name: Print changed files
      if  : steps.changed-files-specific.outputs.any_changed == 'true'
      run: |
        echo "Files that have changed:"
        for file in ${{ steps.changed-files-specific.outputs.all_changed_files }}
         do
           echo $file
         done


    # - name: Run Checkov action
    #   id  : checkov
    #   uses: bridgecrewio/checkov-action@master
    #   if  : steps.changed-files-specific.outputs.any_changed == 'true'
    #   with:
    #     directory    : ${{ env.TERRAFORM_ROOT_FOLDER }}
    #     quiet        : true
    #     framework    : terraform
    #     output_format: cli
