name: BridgeCrew Security Checks
env:
  TERRAFORM_ROOT_FOLDER : "modules"

on:
  pull_request:
    types: [opened, reopened]

jobs:
  get_modified_folders:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone this repo
      id  : git
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
        persist-credentials: true

    - name: Get Folders with changed files
      id  : changed-folders-array
      uses: tj-actions/changed-files@v35
      with:
        dir_names: true
        json     : true
        files: |
          ${{ env.TERRAFORM_ROOT_FOLDER }}/**

    - name: Create Matrix with changed Folders
      if  : steps.changed-folders-array.outputs.any_changed == 'true'
      id  : changed-folders-matrix
      run : echo "matrix=${{ steps.changed-folders-array.outputs.all_changed_files }}" >> $GITHUB_OUTPUT

    outputs:
      changes_detected: ${{ steps.changed-folders-array.outputs.any_changed }}
      matrix          : ${{ steps.changed-folders-matrix.outputs.matrix }}


  scan_modified_folders:
    runs-on: ubuntu-latest
    needs  : get_modified_folders
    if     : needs.get_modified_folders.outputs.changes_detected == 'true'
    strategy:
      matrix:
        changed_folders: ${{fromJson(needs.get_modified_folders.outputs.matrix)}}

    steps:
    - name: Git clone this repo
      id  : git
      uses: actions/checkout@v3

    - name: Run Checkov action
      id  : checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory    : ${{ matrix.changed_folders }}
        quiet        : true
        output_format: cli
