name: BridgeCrew Security Checks
env:
  TERRAFORM_ROOT_FOLDER : "modules"

on:
  pull_request:
    types: [opened, reopened]

jobs:
  get_terraform_modified_folders:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone this repo
      id  : git
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
        persist-credentials: true

    - name: Get Folders with changed files
      id  : changed-folders
      uses: tj-actions/changed-files@v35
      with:
        dir_names: true
        json     : true
        files: |
          ${{ env.TERRAFORM_ROOT_FOLDER }}/**


    outputs:
      matrix          : ${{ steps.changed-folders.outputs.all_changed_files }}
      changes_detected: ${{ steps.changed-folders.outputs.any_changed }}


  scan_terraform_modified_folders:
    runs-on: ubuntu-latest
    needs  : get_terraform_modified_folders
    if     : get_terraform_modified_folders.outputs.changes_detected == 'true'
    strategy:
      matrix:
        changed_folders: ${{fromJson(needs.get_terraform_modified_folders.outputs.matrix)}}

    steps:
    - name: Print changed files
      run: |
        echo "Files that have changed:"
        eacho ${{ needs.get_terraform_modified_folders.outputs.matrix }}

    - name: Git clone this repo
      id  : git
      uses: actions/checkout@v3


    - name: Run Checkov action
      id  : checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory    : ${{ matrix.changed_folders }}
        quiet        : true
        output_format: cli
#        framework    : terraform
